apiVersion: v1
kind: Service
metadata:
  name: argocd-server
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32326
    - port: 443
      targetPort: 8083
      nodePort: 32327
  selector:
    app.kubernetes.io/name: argocd-server
