apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.namespace }}
  source:
    repoURL: {{ .Values.gitRepo.url }}
    path: charts/argo-cd
    targetRevision: {{ .Values.gitRepo.targetRevision }}
  destination:
    server: {{ .Values.cluster.server }}
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      selfHeal: true