apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: {{ .Values.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.gitRepo.url }}
    path: charts/root-app/
    targetRevision: {{ .Values.gitRepo.targetRevision }}
  destination:
    server: {{ .Values.cluster.server }}
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      selfHeal: true
